springdoc:
  swagger-ui:
    path: /user-service.html

spring:
  application:
    name: user-service
  main:
    #Desactivo el Banner de Spring Boot de consola
    banner-mode: off
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://20.121.214.190:1434;databaseName=user;encrypt=true;trustServerCertificate=true;
    username: sa
    password: nocountry2023
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  kafka:
    template:
      default-topic: account-topic
    consumer:
      bootstrap-servers: 20.121.214.190:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: message-account-consumer

server:
  error:
    include-stacktrace: never
  port: 8082
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: https://s10-14-ft-eurekaserver.azurewebsites.net/eureka
